### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scottfr** [silentmatt/js-expression-eval#15]
What is the license for the expression evaluator.

I'm assuming it is MIT. Is that correct?

**Comment by Fantast** [comment]
Dear author, can you please include the licence in the project? Due to github policy we can't really use the project without the licence provided. Of course, we can't just assume it's MIT.

**Comment by silentmatt** [comment]
I added a LICENSE.txt file specifying the MIT license.

**Comment by Fantast** [comment]
Thanks a lot!
