### ISSUE TITLE
How can I run the tests?

### ISSUE THREAD

**Issue by aharris88** [silentmatt/js-expression-eval#23]
Are the tests using mocha? I tried running the tests in the command line using mocha and couldn't get it to work, so I forked it and made some changes to the file, but I'm not sure I did it right. https://github.com/aharris88/js-expression-eval/commit/116b3206a5a3630114714b3f754ae41d5208daa1

So, how do you run the tests?

**Comment by silentmatt** [comment]
They're written to run in RingoJS (http://ringojs.org/, think node.js but Java/Rhino instead of V8) and probably won't run anywhere else. That's probably not a popular choice at the moment, but it's what I was using at the time. I've never used Mocha, but what you have looks reasonable.

**Comment by aharris88** [comment]
Yeah, what I have mostly works, but I couldn't get `it('should convert to js'...` to work and I wasn't even sure how to import Parser. I ended up doing this:

    var Parser = require("./parser");
    Parser = Parser.Parser;

which is weird. Can you give me some instructions on how to run the tests with ringojs. I don't really care what testing framework there is, but I want to be able to test it. I might even need to add some features.

**Comment by escopecz** [comment]
:+1:  I'd also like to create tests for me PR. No idea how to run them...

**Comment by silentmatt** [comment]
The tests are using the built-in testing framework from RingoJS, so probably won't run in another environment.

I'll work on converting this to a Node.js module and Mocha (or another test framework) so the tests are runnable for more people.

**Comment by escopecz** [comment]
I just started to rewrite the tests to Mocha. It'll be part of my PR.

**Comment by escopecz** [comment]
Mocha tests added to https://github.com/silentmatt/js-expression-eval/pull/31/files

**Comment by silentmatt** [comment]
Thanks for the tests @escopecz!
